// MasterMind-Game
/First javaScript Project

//function to generate the computer's choice of color
function playGame() {
	var color = ["r", "g", "b", "y"];//array for the color to be generated by the computer
	var count = 0;
	for (count; count < color.length; count++) {
		var randomNumber = color[Math.floor(Math.random() * color.length)];
		var compChoice = [];
		compChoice.push(randomNumber);//this pushes the value generated at random into the array as the computer choice
	}
	return compChoice.join(""); /*this joins the elements of the array created into strings and 
	returns it to the caller*/ 
}

/*function to compare the player's guess
compared with the computer's random pick, loops 12 times which is the number of try the player's got*/
function compareGuess() {
	var i = 0
	for (i; i <= 11; i++) {

		compareGuess = 0;
		l = Math.min(compChoice.length, userGuess.length);
		
		for( j=0; j<l; j++) {

			if( compChoice.charAt(j) == userGuess.charAt(j)) compareNum++;//comparing the two values
			
		}

		alert()
	}

}


alert("welcome to MASTERMIND");
var choice = prompt("Would you like to (p)lay, read the (i)nstructions, or (q)uit?").toLowerCase();

if (choice === "p" || choice === "play") {
	
	playGame();

	alert("I have generated a beginner sequence with four elements made up of: (r)ed,
(g)reen, (b)lue, and (y)ellow. Use (q)uit at any time to end the game.");

	var userGuess = prompt("What's your guess?...enter it without a comma").toLowerCase();
	
	if (userGuess.length < 4) {
		userGuess = prompt("the guess you entered is incomplete, please re-enter it");
	}
	else
	{
		compareGuess();
	}
	compareGuess();
}

else if (choice === "i" || choice === "instructions") {
//the instruction function will be called here
}

else if (choice === "q" || choice === "quit") {
//the quit function will be called here
}
else {
	prompt("You have entered an invalid option, please try again");
}
